### ISSUE TITLE
请问移动6145F3的猫如何才能删除TR09？谢谢

### ISSUE THREAD

**Issue by yishion819** [nature2608/SuperFH#3]

**Comment by nature2608** [comment]
超密进去就能删了啊

**Comment by yishion819** [comment]
> 超密进去就能删了啊

我这里超密进去后，tr09的保存和删除是灰色的……

**Comment by yishion819** [comment]
用调试删除的话，会把iternet 删除掉，改地区的话，tr09也是灰色的

**Comment by nature2608** [comment]
那就不知道了，我的6145f3好像没这个问题，telnet好像是每次重启都会关掉的。除了调试删掉可以试试用postman等工具构造相同参数调用试试

**Comment by yishion819** [comment]
> 那就不知道了，我的6145f3好像没这个问题，telnet好像是每次重启都会关掉的。除了调试删掉可以试试用postman等工具构造相同参数调用试试

我感觉是固件版本的问题，我是RP02M1的固件，麻烦看下你的，谢谢

**Comment by nature2608** [comment]
RP020a

**Comment by yishion819** [comment]
> RP020a

果然固件不同
