### ISSUE TITLE
请求添加使用方法介绍

### ISSUE THREAD

**Issue by 0xabandon** [nature2608/SuperFH#9]
文件代码下载后不知道如何运行

**Comment by nature2608** [comment]
你下载的源码？源码vs打开运行就可以了。只要可执行文件在旁边release里面。

**Comment by 0xabandon** [comment]
是default.exe文件吗？我点开后没反应。
源码vs打开运行显示“没有用于调试XML的扩展”

**Comment by nature2608** [comment]
项目用vs打开这个“一键获取烽火光猫超密.sln“，直接用打开default.exe

**Comment by 0xabandon** [comment]
两种方法我都尝试了,default.exe点开后没反应。
项目用vs打开“一键获取烽火光猫超密.sln“,显示“没有用于调试纯文本的扩展”

**Comment by nature2608** [comment]
你确定把整个项目都下载下来了？default.exe是.net 4.8编译的，只支持win10以上系统。请自己检查一下环境，这就是个再普通不过的应用程序了。

**Comment by 0xabandon** [comment]
问题已解决,该程序似乎仅支持win10,不支持win11

**Comment by ChrisYH20** [comment]
> 问题已解决,该程序似乎仅支持win10,不支持win11

我在win11上运行没有问题
